networks:
  devcontainer:
    internal: false
services:
  devcontainer:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    command: 'sleep infinity'
    depends_on:
      mysql:
        condition: 'service_healthy'
      nginx:
        condition: 'service_healthy'
      php:
        condition: 'service_healthy'
      valkey:
        condition: 'service_healthy'
    environment:
      APP_ENV: 'local'
      MYSQL_DATABASE: 'db'
      MYSQL_HOST: 'mysql'
      MYSQL_ROOT_PASSWORD: '/run/secrets/mysql_root_password'
      MYSQL_ROOT_USER: 'root'
      MYSQL_UNIT_DATABASE: 'db_unit'
      NODE_ENV: 'development'
    networks:
      - 'devcontainer'
      - 'mysql'
      - 'nginx'
      - 'php'
      - 'valkey'
    secrets:
      - 'mysql_root_password'
    user: 'devcontainer'
    volumes:
      - './:/var/www/html'
  nginx:
    ports:
      - '8080:8080'
    volumes:
      - './:/var/www/html'
  php:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    environment:
      APP_ENV: 'local'
      NODE_ENV: 'development'
    volumes:
      - './:/var/www/html'
