networks:
  devcontainer:
    internal: false
services:
  devcontainer:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    command: 'sleep infinity'
    depends_on:
      mysql:
        condition: 'service_healthy'
      nginx:
        condition: 'service_healthy'
      php:
        condition: 'service_healthy'
      valkey:
        condition: 'service_healthy'
    environment:
      APP_ENV: 'local'
      COMPOSER_CACHE_DIR: '/home/devcontainer/.composer/cache'
      MYSQL_DATABASE: 'db'
      MYSQL_HOST: 'mysql'
      MYSQL_ROOT_PASSWORD: '/run/secrets/mysql_root_password'
      MYSQL_ROOT_USER: 'root'
      MYSQL_UNIT_DATABASE: 'db_unit'
      NODE_ENV: 'development'
      NPM_CONFIG_CACHE: '/home/devcontainer/.npm'
    init: true
    networks:
      - 'devcontainer'
      - 'mysql'
      - 'nginx'
      - 'php'
      - 'valkey'
    secrets:
      - 'mysql_root_password'
    user: 'devcontainer:devcontainer'
    volumes:
      - './:/var/www/html'
      - 'composer-cache:/home/devcontainer/.composer/cache'
      - 'npm-cache:/home/devcontainer/.npm'
  nginx:
    ports:
      - '8080:8080'
    volumes:
      - './:/var/www/html'
  php:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    environment:
      APP_ENV: 'local'
      NODE_ENV: 'development'
    volumes:
      - './:/var/www/html'
volumes:
  composer-cache:
    external: true
    name: 'tomaschochola-composer-cache'
  npm-cache:
    external: true
    name: 'tomaschochola-npm-cache'
