networks:
  devcontainer:
    internal: false
services:
  devcontainer:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    command: 'sleep infinity'
    depends_on:
      mysql:
        condition: 'service_healthy'
      nginx:
        condition: 'service_healthy'
      php:
        condition: 'service_healthy'
      valkey:
        condition: 'service_healthy'
    environment:
      APP_ENV: 'local'
      COMPOSER_CACHE_DIR: '/home/devcontainer/.composer'
      MYSQL_DATABASE: 'db'
      MYSQL_HOST: 'mysql'
      MYSQL_PASSWORD_FILE: '/run/secrets/db_password'
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/db_root_password'
      MYSQL_USER: 'db'
      NODE_ENV: 'development'
      npm_config_cache: '/home/devcontainer/.npm'
    networks:
      - 'devcontainer'
      - 'mysql'
      - 'nginx'
      - 'php'
      - 'valkey'
    secrets:
      - 'db_password'
      - 'db_root_password'
    user: 'devcontainer'
    volumes:
      - './:/var/www/html'
      - 'global_composer_cache:/home/devcontainer/.composer'
      - 'global_npm_cache:/home/devcontainer/.npm'
  nginx:
    volumes:
      - './:/var/www/html'
  php:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    environment:
      APP_ENV: 'local'
      NODE_ENV: 'development'
    volumes:
      - './:/var/www/html'
volumes:
  global_composer_cache:
    external: true
  global_npm_cache:
    external: true
